---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver only on ubuntu nodes
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"
  - name: install webserver only on RedHat nodes
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"